apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: appliance-tracker

resources:
  - namespace.yaml
  - onepassword-item.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
