apiVersion: v1
kind: Service
metadata:
  name: appliance-tracker
  namespace: appliance-tracker
  labels:
    app.kubernetes.io/name: appliance-tracker
    app.kubernetes.io/component: web
spec:
  selector:
    app.kubernetes.io/name: appliance-tracker
    app.kubernetes.io/component: web
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
  type: ClusterIP
